I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 88, in script
    "\"We had to lie down with many people, one on top of the other. The coyotes [smugglers] put cardboard on top of us so la Migra [the authorities] wouldn’t see us if they pulled us over.\""
NameError: name 'smugglers' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 88, in script
    "\"We had to lie down with many people, one on top of the other. The coyotes [smugglers] put cardboard on top of us so la Migra [the authorities] wouldn’t see us if they pulled us over.\""
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/ast.py", line 2586, in execute
    Say.execute(self)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/exports/sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/character.py", line 1456, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/character.py", line 1369, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/character.py", line 1349, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/substitutions.py", line 86, in interpolate
    raise e
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/jonas/Code/Ren'Py/Ren'Py SDK/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'smugglers' is not defined

macOS-15.1.1-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
Proyecto Final 1.0
Fri Apr 25 12:15:47 2025
